apiVersion: 1
datasources:
  - name: InfluxDB
    uid: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: sensors
    secureJsonData:
      token: studybuddy_admin_token_123
